name: CI

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install ncurses
        # Check if cmake is already installed, if not install it
        if ! command -v cmake &> /dev/null; then
          brew install cmake
        fi

    - name: Configure build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_BUILD_TYPE=Release ..

    - name: Build
      run: |
        cd build
        make -j$(sysctl -n hw.ncpu)

    - name: Test
      run: |
        cd build
        # Basic smoke test - run briefly and check exit code
        timeout 5 ./smon || true
        # Check if binary was created and is executable
        if [ -x "./smon" ]; then
          echo "✓ Binary created successfully"
        else
          echo "✗ Binary creation failed"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: smon-macos-arm64
        path: build/smon
        retention-days: 30

    - name: Create release archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd build
        zip -r ../smon-macos-arm64.zip smon

    - name: Create Release
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Changes

          See [changelog](https://github.com/barturba/smon/compare/${{ github.event.repository.default_branch }}...${{ github.ref }}) for details.

          ## Downloads

          - **smon-macos-arm64.zip**: Compiled binary for macOS Apple Silicon (ARM64)
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./smon-macos-arm64.zip
        asset_name: smon-macos-arm64.zip
        asset_content_type: application/zip
